package com.example.servico_restful.Entities.PojoEntities;

public class ActorPojo {
    public String id;
    public String type;
    public String login;
    public String avatar_url;
    public Object __updated_at;
    public Object bio;
    public Object company;
    public Object created_at;
    public Object database_id;
    public Object email;
    public Object followers;
    public Object following;
    public Object gists;
    public Object is_bounty_hunter;
    public Object is_campus_expert;
    public Object is_developer_program_member;
    public Object is_employee;
    public Object is_hireable;
    public Object is_site_admin;
    public Object location;
    public Object name;
    public Object projects;
    public Object projects_url;
    public Object repositories;
    public Object repositories_contributed_to;
    public Object starred_repositories;
    public Object status;
    public Object twitter_username;
    public Object updated_at;
    public Object watching;
    public Object website_url;
    public Object description;
    public Object is_verified;
    public Object members_with_role;
    public Object teams;
    public Object user;
}
